[general]
name = "basic_error_checking_example"
version = "0.1.0"
description = "Basic configuration for error checking in Solvespace"

[error_checking]
# Tolerance settings
position_tolerance = 1e-6  # in mm
angle_tolerance = 1e-4     # in radians
constraint_tolerance = 1e-5

# Checking parameters
check_overconstrained = true
check_redundant_constraints = true
check_undefined_references = true
check_sketch_closures = true

# Display settings for errors
highlight_errors = true
error_color = [255, 0, 0]  # RGB color for error display

[debug]
verbose_errors = false
log_file = "slvs_errors.log"
